### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-opioid-epidemic-demo#1]
- [ ] This Dash app is only 300 lines of code, but most of it is generating the map. Replace this code with a choropleth map [figure factory](https://github.com/plotly/plotly.py/blob/master/plotly/figure_factory/README.md).

- [ ] Updating CSS for the [plotly styleguide](brand.plot.ly)

- [ ] Updating the map colorscale is slow because it re-generates the map everytime. Use [`Plotly.react`](https://github.com/plotly/react-plotly.js/issues/2) when it becomes available for Dash.
